#
# trillian_history config file
#

general:
  timezone: US/Eastern
  source_dir: ~/Dropbox/documents/logs/trillian/logs
  working_dir: tmp
  output_dir: output
  exclude_users:
    - users

pelican:
  bin: env/bin/pelican
  config: pelicanconfig.py
